const questionsData = [
    {
      title: "How to implement authentication in React?",
      description: "I'm building a React application and need to implement user authentication. What are the best practices?",
      author: "John Doe",
      time: "2 hours ago",
      tags: ["React", "Authentication", "JavaScript"],
      answers: 3,
      initialVotes: 5
    },
    {
      title: "Best practices for state management in large applications",
      description: "What are the recommended patterns for managing state in large-scale React applications?",
      author: "Jane Smith",
      time: "4 hours ago",
      tags: ["React", "State Management", "Redux"],
      answers: 7,
      initialVotes: 12
    },
    {
      title: "How to optimize React app performance?",
      description: "My React application is running slowly. What are some techniques to improve performance?",
      author: "Mike Johnson",
      time: "1 day ago",
      tags: ["React", "Performance", "Optimization"],
      answers: 5,
      initialVotes: 8
    },
    {
      title: "Understanding React Hooks",
      description: "Can someone explain the concept of React Hooks and when to use them?",
      author: "Sarah Wilson",
      time: "2 days ago",
      tags: ["React", "Hooks", "JavaScript"],
      answers: 2,
      initialVotes: 6
    },
    {
      title: "CSS Grid vs Flexbox - When to use which?",
      description: "I'm confused about when to use CSS Grid and when to use Flexbox. Can someone clarify?",
      author: "Alex Brown",
      time: "3 days ago",
      tags: ["CSS", "Grid", "Flexbox"],
      answers: 4,
      initialVotes: 10
    }
  ];

  const filterConfig = {
    tags: {
      title: "Tags",
      items: [
        { id: "notices", label: "Notices" },
        { id: "events", label: "Events" },
        { id: "counselling", label: "Counselling" },
        { id: "resources", label: "Resources" },
        { id: "workshops", label: "Workshops" },
        { id: "mentorship", label: "Mentorship" },
        { id: "internships", label: "Internships" },
        { id: "placements", label: "Placements" },
        { id: "hackathons", label: "Hackathons" },
        { id: "competitions", label: "Competitions" },
        { id: "seminars", label: "Seminars" },
        { id: "webinars", label: "Webinars" },
        { id: "conferences", label: "Conferences" },
        { id: "meetups", label: "Meetups" },
        { id: "bootcamps", label: "Bootcamps" },
      ],
    },
    department: {
      title: "Department",
      items: [
        { id: "cs", label: "Computer Science" },
        { id: "it", label: "Information Technology" },
        { id: "ece", label: "Electronics & Communication" },
        { id: "me", label: "Mechanical Engineering" },
        { id: "ce", label: "Civil Engineering" },
        { id: "ee", label: "Electrical Engineering" },
        { id: "mba", label: "MBA" },
        { id: "mca", label: "MCA" },
        { id: "chem", label: "Chemical Engineering" },
        { id: "bio", label: "Biomedical Engineering" },
        { id: "aero", label: "Aerospace Engineering" },
        { id: "auto", label: "Automobile Engineering" },
        { id: "textile", label: "Textile Engineering" },
        { id: "mining", label: "Mining Engineering" },
        { id: "metal", label: "Metallurgical Engineering" },
        { id: "food", label: "Food Technology" },
        { id: "marine", label: "Marine Engineering" },
        { id: "petro", label: "Petroleum Engineering" },
        { id: "enviro", label: "Environmental Engineering" },
        { id: "agri", label: "Agricultural Engineering" },
        { id: "arch", label: "Architecture" },
        { id: "physics", label: "Physics" },
        { id: "chem2", label: "Chemistry" },
        { id: "math", label: "Mathematics" },
        { id: "bio2", label: "Biology" },
        { id: "biotech", label: "Biotechnology" },
        { id: "micro", label: "Microbiology" },
        { id: "stats", label: "Statistics" },
        { id: "econ", label: "Economics" },
        { id: "bcom", label: "B.Com" },
        { id: "bba", label: "BBA" },
        { id: "finance", label: "Finance" },
        { id: "account", label: "Accounting" },
        { id: "marketing", label: "Marketing" },
        { id: "hr", label: "Human Resources" },
        { id: "law", label: "Law" },
        { id: "english", label: "English Literature" },
        { id: "hindi", label: "Hindi Literature" },
        { id: "history", label: "History" },
        { id: "geo", label: "Geography" },
        { id: "polsci", label: "Political Science" },
        { id: "socio", label: "Sociology" },
        { id: "psych", label: "Psychology" },
        { id: "philo", label: "Philosophy" },
        { id: "journal", label: "Journalism" },
        { id: "mass", label: "Mass Communication" },
        { id: "fashion", label: "Fashion Design" },
        { id: "graphic", label: "Graphic Design" },
        { id: "interior", label: "Interior Design" },
        { id: "fine", label: "Fine Arts" },
        { id: "music", label: "Music" },
        { id: "dance", label: "Dance" },
        { id: "theatre", label: "Theatre Arts" },
        { id: "film", label: "Film Studies" },
        { id: "photo", label: "Photography" },
        { id: "nursing", label: "Nursing" },
        { id: "pharma", label: "Pharmacy" },
        { id: "dental", label: "Dental" },
        { id: "physio", label: "Physiotherapy" },
        { id: "medical", label: "Medical" },
      ],
    },
    academicYear: {
      title: "Academic Year",
      items: [
        { id: "first", label: "First Year" },
        { id: "second", label: "Second Year" },
        { id: "third", label: "Third Year" },
        { id: "fourth", label: "Final Year" },
      ],
    },
    category: {
      title: "Category",
      items: [
        { id: "academic", label: "Academic" },
        { id: "career", label: "Career Development" },
        { id: "technical", label: "Technical" },
        { id: "social", label: "Social Service" },
      ],
    },
  };

  export {questionsData, filterConfig};