const questionsData = [
    {
      title: "Math 1 Notes",
      author: "Girish Garg",
      uploadDate: "12/11/2025",
      tags: ["Student", "Math 1", "Civil Sem", "Notes"],
    },
    {
      title: "Physics Notes",
      author: "Ankit Sharma",
      uploadDate: "10/10/2025",
      tags: ["Student", "Physics", "Sem 2", "Notes"],
    },
    {
      title: "Java Programming",
      author: "Neha Verma",
      uploadDate: "15/11/2025",
      tags: ["Student", "Java", "CS", "Code"],
    },
    {
      title: "Environmental Studies",
      author: "Sanya Jain",
      uploadDate: "11/11/2025",
      tags: ["Student", "EVS", "Sem 1", "PDF"],
    },
    {
      title: "BEEE Lab Manual",
      author: "Rajat Saxena",
      uploadDate: "14/11/2025",
      tags: ["Student", "Electrical", "Lab", "Manual"],
    },
    {
      title: "Engineering Mechanics",
      author: "Deepak Sinha",
      uploadDate: "13/11/2025",
      tags: ["Student", "Mechanics", "Sem 2", "Notes"],
    },
    {
      title: "Civil Engineering Survey",
      author: "Aarti Gupta",
      uploadDate: "12/11/2025",
      tags: ["Student", "Survey", "Civil", "Practical"],
    },
    {
      title: "Workshop Drawing",
      author: "Mayank Mehta",
      uploadDate: "10/11/2025",
      tags: ["Student", "Drawing", "Mechanical", "Notes"],
    },
    {
      title: "HTML and CSS",
      author: "Ritika Yadav",
      uploadDate: "12/11/2025",
      tags: ["Student", "Web Dev", "CS", "Notes"],
    },
    {
      title: "HTML and CSS",
      author: "Ritika Yadav",
      uploadDate: "12/11/2025",
      tags: ["Student", "Web Dev", "CS", "Notes"],
    },
    {
      title: "HTML and CSS",
      author: "Ritika Yadav",
      uploadDate: "12/11/2025",
      tags: ["Student", "Web Dev", "CS", "Notes"],
    },
    {
      title: "HTML and CSS",
      author: "Ritika Yadav",
      uploadDate: "12/11/2025",
      tags: ["Student", "Web Dev", "CS", "Notes"],
    },
    {
      title: "HTML and CSS",
      author: "Ritika Yadav",
      uploadDate: "12/11/2025",
      tags: ["Student", "Web Dev", "CS", "Notes"],
    },
  ];

  const filterConfig = {
    tags: {
      title: "Tags",
      items: [
        { id: "notices", label: "Notices" },
        { id: "events", label: "Events" },
        { id: "counselling", label: "Counselling" },
        { id: "resources", label: "Resources" },
        { id: "workshops", label: "Workshops" },
        { id: "mentorship", label: "Mentorship" },
        { id: "internships", label: "Internships" },
        { id: "placements", label: "Placements" },
        { id: "hackathons", label: "Hackathons" },
        { id: "competitions", label: "Competitions" },
        { id: "seminars", label: "Seminars" },
        { id: "webinars", label: "Webinars" },
        { id: "conferences", label: "Conferences" },
        { id: "meetups", label: "Meetups" },
        { id: "bootcamps", label: "Bootcamps" },
      ],
    },
    department: {
      title: "Department",
      items: [
        { id: "cs", label: "Computer Science" },
        { id: "it", label: "Information Technology" },
        { id: "ece", label: "Electronics & Communication" },
        { id: "me", label: "Mechanical Engineering" },
        { id: "ce", label: "Civil Engineering" },
        { id: "ee", label: "Electrical Engineering" },
        { id: "mba", label: "MBA" },
        { id: "mca", label: "MCA" },
        { id: "chem", label: "Chemical Engineering" },
        { id: "bio", label: "Biomedical Engineering" },
        { id: "aero", label: "Aerospace Engineering" },
        { id: "auto", label: "Automobile Engineering" },
        { id: "textile", label: "Textile Engineering" },
        { id: "mining", label: "Mining Engineering" },
        { id: "metal", label: "Metallurgical Engineering" },
        { id: "food", label: "Food Technology" },
        { id: "marine", label: "Marine Engineering" },
        { id: "petro", label: "Petroleum Engineering" },
        { id: "enviro", label: "Environmental Engineering" },
        { id: "agri", label: "Agricultural Engineering" },
        { id: "arch", label: "Architecture" },
        { id: "physics", label: "Physics" },
        { id: "chem2", label: "Chemistry" },
        { id: "math", label: "Mathematics" },
        { id: "bio2", label: "Biology" },
        { id: "biotech", label: "Biotechnology" },
        { id: "micro", label: "Microbiology" },
        { id: "stats", label: "Statistics" },
        { id: "econ", label: "Economics" },
        { id: "bcom", label: "B.Com" },
        { id: "bba", label: "BBA" },
        { id: "finance", label: "Finance" },
        { id: "account", label: "Accounting" },
        { id: "marketing", label: "Marketing" },
        { id: "hr", label: "Human Resources" },
        { id: "law", label: "Law" },
        { id: "english", label: "English Literature" },
        { id: "hindi", label: "Hindi Literature" },
        { id: "history", label: "History" },
        { id: "geo", label: "Geography" },
        { id: "polsci", label: "Political Science" },
        { id: "socio", label: "Sociology" },
        { id: "psych", label: "Psychology" },
        { id: "philo", label: "Philosophy" },
        { id: "journal", label: "Journalism" },
        { id: "mass", label: "Mass Communication" },
        { id: "fashion", label: "Fashion Design" },
        { id: "graphic", label: "Graphic Design" },
        { id: "interior", label: "Interior Design" },
        { id: "fine", label: "Fine Arts" },
        { id: "music", label: "Music" },
        { id: "dance", label: "Dance" },
        { id: "theatre", label: "Theatre Arts" },
        { id: "film", label: "Film Studies" },
        { id: "photo", label: "Photography" },
        { id: "nursing", label: "Nursing" },
        { id: "pharma", label: "Pharmacy" },
        { id: "dental", label: "Dental" },
        { id: "physio", label: "Physiotherapy" },
        { id: "medical", label: "Medical" },
      ],
    },
    academicYear: {
      title: "Academic Year",
      items: [
        { id: "first", label: "First Year" },
        { id: "second", label: "Second Year" },
        { id: "third", label: "Third Year" },
        { id: "fourth", label: "Final Year" },
      ],
    },
    category: {
      title: "Category",
      items: [
        { id: "academic", label: "Academic" },
        { id: "career", label: "Career Development" },
        { id: "technical", label: "Technical" },
        { id: "social", label: "Social Service" },
      ],
    },
  };

  export { questionsData, filterConfig };